# Constants

INTRODUCTION = """Welcome to Midnight Rider
WE'VE STOLEN A CAR. WE NEED TO GET IT HOME.
THE CAR IS SPECIAL.
THAT'S WHY THE GOVERNMENT WANTS IT.
WE CAN'T LET THEM HAVE IT.
ONE GOAL: SURVIVAL... AND THE CAR
REACH THE SAFEHOUSE BEFORE THE MAN
GON GETCHU.
"""

CHOICES = """
    --- Your Choices ---
    A. Eat a tofu
    B. Travel moderately
    C. Speed ahead at full speed
    D. Stop to refuel
    E. Check current status
    Q. Quit the game
    ---
"""

REFUEL = """-------You filled the fuel tank.
-------The agents got closer...
"""

EAT_TOFU = """-------Mmmmm. Soybean goodness.
-------Your hunger is sated.
"""

NO_TOFU = """-------You have no tofu left. Have fun starving!
"""

SEVERE_HUNGER = """*******Your stomach rumbles.
*******You need to eat something quick.
"""

HUNGER = """*******Your hunger is small but manageable.
"""

ENDGAME_TEXT = [
    """The game has ended. Thanks for playing""", # quit game
    """\n\nTHE AGENTS HAVE CLOSED IN ON YOU.
THERE ARE AT LEAST 20 CARS SURROUNDING YOU.
THE LEAD CAR  BUMPS YOUR PASSENGER SIDE.
YOU MANAGE TO CORRECT YOUR STEERING
TO KEEP YOU FROM CRASHING


YOU DIDN'T SEE THE AGENT'S CAR RIGHT BESIDE YOU.
THAT DRIVER BUMPED YOUR CAR
AND THAT'S IT

YOU SPIN UNCONTROLLABLY
YOUR CAR FLIPS OVER AT LEAST TWO TIMES
OR MORE... YOU SEEM TO HAVE LOSE COUNT

SIRENS.

"ARE THEY ALIVE? THEY SAY AS YOU HEAR
FOOTSTEPS COMING CLOSER.
"DOESN'T MATTER, ALL WE WANTED WAS GTE CAR."

YOU SEE A DOG SLOWLY STEP OUT OF THE 
OVERTURNED CAR.

"YOU WILL NEVER STOP THE REVOLUTION!"
THE DOG SEEMS TO SAY TO THE AGENTS.

IT WAS IN THE CAR THE WHOLE TIME

YOU DRIFT OFF INTO UNCOUNSCIOUSNESS...

-GAME END """,    #Lose - agents have caught up

    """\n\nYOUR CAR SPUTTERS AND SEEMS TO LET OUT
A BIG SIGH, THERE'S NO MORE FUEL LEFT.

THE AGENTS SURROUND YOU AND STEP OUT
OF THEIR CAR. THE LEAD AGENT RIPS
THE DOOR OPEN AND THROWS YOU OUT OF
YOUR CAR.

"WE FINALLY GOT IT."

YOU FAILED.""",

    """\n\nYOUR STOMACH IS EMPTY.
WHO KNEW THAT WHAT THE DOCTOR SAID WAS TRUE,
THAT HUMAN/ROBOT HYBRIDS WOULD NEED
TOFU TO SUSTAIN THEMSELVES.
YOUR ROBOT SYSTEMS START TO SHUT DOWN.
YOUR HUMAN EYES CLOSE.
THE LAST THING THAT YOU HEAR ARE SIRENS.
THEY GOTCHU. THEY GOT THE CAR.
WE FAILED..."""

]